name: FarmerMigrate
version: '${project.version}'
main: me.waterarchery.farmermigrate.FarmerMigrate
api-version: 1.13
author: WaterArchery
commands:
  farmermigrate:
    description: migrate command
depend:
  - Farmer